### ISSUE TITLE
使用pyinstaller构建的exe启动失败

### ISSUE THREAD

**Issue by Puiching-Memory** [xufive/wxgl#2]
我在尝试使用pyinstaller构建的exe时启动失败:

-------------------------这是错误返回------------------------------
>> .\M_WxGL.exe
Traceback (most recent call last):
  File "M_WxGL.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "wxgl\scene.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "wxgl\fm.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "freetype\__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "freetype\raw.py", line 196, in <module>
  File "ctypes\__init__.py", line 386, in __getattr__
  File "ctypes\__init__.py", line 391, in __getitem__
AttributeError: function 'FTC_CMapCache_Lookup' not found
[17284] Failed to execute script 'M_WxGL' due to unhandled exception!

-------------------------这是打包指令------------------------------
>>pyinstaller -D M_WxGL.py

-------------------------错误描述------------------------------
我使用wxgl库写了一个可以正常运行的PY文件,它只有显示一个正方体和3D坐标系的功能.
我尝试将它打包成可执行文件exe,可却不能正常工作,请告诉我如果解决它!
我将在以下附上我的代码:
[Code.zip](https://github.com/xufive/wxgl/files/7798593/Code.zip)

**Comment by xufive** [comment]
请使用当前版本，参考最新文档。
Please use the current version and refer to the latest documents.

**Comment by Puiching-Memory** [comment]
我已经查清并解决了该问题：

-----错误原因-----
wxgl依赖项中的“freetype-py”模块
该模块不能被pyinstaller正确识别并打包

-----解决方法-----
在pyinstaller打包命令中手动添加该模块名字
`--collect-all freetype`

完整指令：
`pyinstaller -D M_Import_OBJ.py --noconfirm -d all --collect-all freetype`

-----注意事项-----
在freetype模块中有这样一段注释：（位于’freetype>__init__‘文件）
Note: C Library will be searched using the ctypes.util.find_library. However,this search might fail. In such a case (or for other reasons), you may have to specify an explicit path below.
（注意：C库将使用ctypes进行搜索。然而搜索可能会失败。在这种情况下（或出于其他原因），您可以必须在下面指定一个显式路径。）

-----版本-----
wxgl--0.9.2
pyinstaller--4.10

**Comment by Puiching-Memory** [comment]
@xufive 请验证该方法的可行性，谢谢！

**Comment by xufive** [comment]
> 我已经查清并解决了该问题：
> 
> -----错误原因----- wxgl依赖项中的“freetype-py”模块 该模块不能被pyinstaller正确识别并打包
> 
> -----解决方法----- 在pyinstaller打包命令中手动添加该模块名字 `--collect-all freetype`
> 
> 完整指令： `pyinstaller -D M_Import_OBJ.py --noconfirm -d all --collect-all freetype`
> 
> -----注意事项----- 在freetype模块中有这样一段注释：（位于’freetype>**init**‘文件） Note: C Library will be searched using the ctypes.util.find_library. However,this search might fail. In such a case (or for other reasons), you may have to specify an explicit path below. （注意：C库将使用ctypes进行搜索。然而搜索可能会失败。在这种情况下（或出于其他原因），您可以必须在下面指定一个显式路径。）
> 
> -----版本----- wxgl--0.9.2 pyinstaller--4.10

确实如此，collect有效。因为网络原因，未能成功下载你提供的zip，我猜测你的源码使用的是wxgl.glplot，不是在wxPython使用wxgl，因为后者打包的话，需要增加-w参数。打包一个wxPython应用，完整的命令如下：

 `pyinstaller -D M_Import_OBJ.py --noconfirm -w -d all --collect-all freetype`
