### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by qichikimochi** [xufive/wxgl#3]
`import numpy as np
import wxgl.wxplot as plt
vs = np.array([
    [1,-1,1], [1,-1,-1], [1,1,-1], [1,1,1],
    [-1,1,1], [-1,1,-1], [-1,-1,-1], [-1,-1,1], 
    [-1,-1,1], [-1,-1,-1], [1,-1,-1], [1,-1,1], 
    [1,1,1], [1,1,-1], [-1,1,-1], [-1,1,1]
])
Img = b'F:/Data/Image/bull.jpg'
plt.surface(vs, texture=Img, alpha=False)
plt.show(rotation='h+')
`
error:
Traceback (most recent call last):
a.py", line 10, in <module>
    plt.surface(vs, texture=Img, alpha=False)
  File "C:\Programs\Python\Python38\lib\site-packages\wxgl\wxplot.py", line 54, in wrapper
    func(*args, **kwds)
  File "C:\Programs\Python\Python38\lib\site-packages\wxgl\wxplot.py", line 131, in surface
    fig.curr_ax.surface(*args, **kwds)
  File "C:\Programs\Python\Python38\lib\site-packages\wxgl\axes.py", line 490, in surface
    raise ValueError('当参数texture有效时，期望texcoord有效')
ValueError: 当参数texture有效时，期望texcoord有效

**Comment by xufive** [comment]
请使用当前版本，参考最新文档。
Please use the current version and refer to the latest documents.
